# Generated by Django 3.1.7 on 2021-03-17 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_categoria_sigla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='sigla',
        ),
    ]
