# Generated by Django 3.1.7 on 2021-03-24 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_auto_20210324_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='novocampo',
        ),
    ]
