version: "3.3"

services:
  homo:
    build: .
    command: bash -c "python manage.py migrate && python manage.py test && python manage.py runserver 0.0.0.0:8001"
    ports:
      - 8001:8001
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    build: ./nginx
    volumes: 
      - .:/static
    ports: 
      - 80:81
    depends_on:
      - homo
    

volumes:
  postgres_data: