version: "3.3"

services:
  homo:
    build: .
    command: bash -c "python manage.py migrate && python manage.py test && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    build: ./nginx
    volumes: 
      - .:/static
    ports: 
      - 80:80
    depends_on:
      - homo
    

volumes:
  postgres_data: