version: "3.3"

services:
  prod:
    build: .
    command: bash -c "python manage.py migrate && python manage.py createsuperuser "admin" "admin" && python manage.py test && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db-prod
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - db-prod
  db-prod:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
  nginx-prod:
    build: ./nginx-prod
    volumes: 
      - .:/static-prod
    ports: 
      - 80:80
    depends_on:
      - prod
    

volumes:
    postgres_data_prod: