version: "3.3"

services:
  homo:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8001
    depends_on:
      - db_homo
  db_homo:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx_homo:
    build: ./nginx-homo
    volumes: 
      - .:/static
    ports: 
      - 80:81
    depends_on:
      - homo
    

volumes:
  postgres_data: