# Generated by Django 3.1.7 on 2021-03-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_categoria_lancamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('D', 'Despesas'), ('R', 'Receitas')], default='D', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='tipo',
            field=models.CharField(choices=[('D', 'Despesas'), ('R', 'Receitas')], max_length=1),
        ),
    ]
