# Generated by Django 3.1.7 on 2021-03-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_auto_20210316_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='sigla',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
