# Generated by Django 3.1.7 on 2021-03-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_remove_categoria_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='novocampo',
            field=models.CharField(choices=[('D', 'Despesas'), ('R', 'Receitas')], max_length=1, null=True),
        ),
    ]
