# Generated by Django 3.1.7 on 2021-03-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_categoria_novocampo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('D', 'Despesas'), ('R', 'Receitas')], max_length=31),
        ),
    ]
