# Generated by Django 3.2.4 on 2021-06-30 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_auto_20210627_2117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipo',
            new_name='Teste',
        ),
    ]
