# Generated by Django 3.2.4 on 2021-06-30 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_rename_tipo_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
